server:
  port: 8080
spring:
  application:
    name: "GymProject"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://jaras:jaras123@miprimerbase.h0qru.mongodb.net/gym?retryWrites=true&w=majority"
